- id: copyright-license-disclaimer
  name: copyright-license-disclaimer
  entry: copyright-license-disclaimer
  language: python
  types: [python]
  args: [--fix-in-place]
- id: sigoptlint-python
  name: sigoptlint-python
  entry: sigoptlint-python
  language: python
  types: [python]
- id: sigoptlint-shell
  name: sigoptlint-shell
  entry: sigoptlint-shell
  language: python
  types: [shell]
