ci:
  skip: [detect-aws-credentials]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch=main]
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
        args: [--maxkb=256]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/sigopt/sigopt-tools.git
    rev: "v0.0.2"
    hooks:
      - id: copyright-license-disclaimer
        args: ["--license=Apache License 2.0", "--owner=Intel Corporation"]
      - id: sigoptlint-python
  - repo: https://github.com/sigopt/black.git
    rev: sigopt-22.10.0
    hooks:
      - id: black
        args: [--preview]
  - repo: https://github.com/PyCQA/flake8.git
    rev: "7.1.0"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print==4.0.0
        args: [--config=setup.cfg]
  - repo: https://github.com/PyCQA/isort.git
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
  - repo: https://github.com/jendrikseipp/vulture.git
    rev: "v2.11"
    hooks:
      - id: vulture
  - repo: https://github.com/pylint-dev/pylint.git
    rev: "v3.2.3"
    hooks:
      - id: pylint
        entry: env PYTHONPATH=. pylint
        args: [-rn, -sn]
        additional_dependencies:
          - pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: env PYTHONPATH=. pytest
        additional_dependencies:
          - pytest
        language: python
        types: [python]
        stages: [commit]
        pass_filenames: false
        always_run: true
