- id: copyright-license-disclaimer
  name: copyright-license-disclaimer
  entry: copyright-license-disclaimer --fix-in-place
  language: python
  types: [python]
- id: sigoptlint-python
  name: sigoptlint-python
  entry: sigoptlint-python
  language: python
  types: [python]
- id: sigoptlint-shell
  name: sigoptlint-shell
  entry: sigoptlint-shell
  language: python
  types: [shell]
