title = 'SigOpt Tools'

[tool.black]
line-length = 120

[tool.mypy]
follow_imports = 'skip'

disable_error_code = 'name-defined,var-annotated'

[tool.vulture]
paths = ['.']
exclude = [
  '.venv',
  'venv',
]
